linters-settings:
  errcheck:
    check-type-assertions: true

  goconst:
    min-len: 2
    min-occurrences: 5

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  govet:
    check-shadowing: true

  nolintlint:
    require-explanation: true
    require-specific: true

  testpackage:
    skip-regexp: internal_test\.go

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - gci
    - goconst
    - gocritic
    - goerr113
    - gofmt
    - goimports
    - gomnd
    - gocyclo
    - gosimple
    - govet
    - ifshort
    - ineffassign
    - importas
    - misspell
    - nilerr
    - nolintlint
    - nakedret
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace
    - wsl

run:
  issues-exit-code: 1
