linters-settings:
  errcheck:
    check-type-assertions: true

  goconst:
    min-len: 2
    min-occurrences: 5

  depguard:
    rules:
      main:
        allow:
          - github.com/mailund/gostr
          - $gostd

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  nolintlint:
    require-explanation: true
    require-specific: true


linters:
  enable-all: true

run:
  issues-exit-code: 1
