name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v ./...

      - name: Run Tests with Coverage
        run: go test -v -coverpkg=./... -coverprofile=coverage.out ./...

      - name: Convert Coverage to LCOV
        run: |
          go install github.com/jandelgado/gcov2lcov@latest
          gcov2lcov -infile coverage.out -outfile coverage.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.lcov  
          flags: unittests
          name: codecov-go
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
